name: Python CI

#Trigger the workflow on events
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest # container
    
    steps:
    # Step 1
    - name: Check out code 
      uses: actions/checkout@v4 # prebuilt code from GitHub repo

    # Step 2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    # Step 3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Step 4
    - name: Run test
      run: pytest
